project:
  type: book

book:
  title: "Introduction to Computational Chemistry"
  author: "Caleb A. Tormey"
  date: "4/30/2026"
  
  chapters:
    - index.qmd
    - part: "Module 1: Foundations & 1D Quantum"
      chapters: 
        - notebooks/week_1_python_primer.ipynb
        - notebooks/week_2_1D_Quantum.ipynb
        - notebooks/week_2_problem_1_finite_well.ipynb
        - notebooks/week_2_problem_2_harmonic_oscillator.ipynb
        
    
    - part: "Appendices"
      chapters:
        - notebooks/appendix_crash_course.qmd
        - notebooks/appendix_linear_algebra.qmd
    - references.qmd

bibliography: references.bib

format:
  live-html: 
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    code-links:
      - text: "Download Notebook Source"
        icon: file-code
        href: https://github.com/Caleb-Tormey-comp-chem-course/blob/master/{path}