# Module A: Introduction 

## Building the Toolkit

Welcome to Computational Chemistry!

Computational chemistry sits at the exact intersection of three different worlds: chemistry, physics, and computer science. Because of this, it is very rare for anyone to walk into this field knowing everything. When I tell people I am a computational chemist I tell them, half joking, I feel like a fraud three times over.  

## Two Paths But One Destination

In this class, we have a mix of backgrounds:

The Chemists [^1]: You might feel very comfortable talking about energy wells, kinetics, and orbitals, but you might feel intimidated by for loops, arrays, and Python syntax.

The Computer Scientists: You might be completely at home debugging algorithms, optimizing matrices, and writing scripts, but you might feel out of your depth when we start talking about Hamiltonians, wavefunctions, and zero-point energy.

This is a feature, not a bug.

My advice for this "textbook" and especially this first module, is to focus heavily on the stuff you have the least experience with. If you are a CS student, use this module to really solidify your mental model of chemical potential energy. If you are a Chemistry student, use this time to get comfortable reading Python error messages. (And if you get stuck, collaborate! You each have the exact expertise the other needs). Also, don't just do the bare minimum. If you are a CS major and you are confused about the Schrödinger equation, spend a little time to understand its importance to chemistry and physics. If you are a chemistry or physics major read up on useful programming and computer science strategies for writing good code. 

Before we can start simulating molecules, we need to make sure everyone's toolbelts are packed with the exact same gear. In this module, we will cover:
* The Physics & Chemistry Refresher: We will review the fundamental concepts of forces, potential energy surfaces, and classical mechanics so we understand the physical rules our simulations must follow.
* Atomic Units: In the real world, we measure mass in kilograms and energy in Joules. In quantum mechanics, those numbers become so absurdly small (like $10^{-34}$) that they cause computers to crash due to floating-point rounding errors. We will learn how to switch to "Atomic Units" (Hartrees and Bohrs) to permanently get rid of messy constants like Planck's constant and the mass of an electron.
* The Python Primer: We aren't going to build software from scratch, but we are going to use professional scientific libraries. You will learn the basics of NumPy for handling large grids of numbers, SymPy for doing calculus automatically, and Matplotlib for graphing our results.

This module is all about setting the stage. Once you understand the physics, the units, and the code, we will be ready to open Module 2 and actually solve some differential equations and eventually the Schrödinger equation!

[^1]: Technically this group also includes physicists but they are just misguided chemsits. 